require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/appoinment_types", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AppoinmentType. As you add validations to AppoinmentType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AppoinmentType.create! valid_attributes
      get appoinment_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      appoinment_type = AppoinmentType.create! valid_attributes
      get appoinment_type_url(appoinment_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_appoinment_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      appoinment_type = AppoinmentType.create! valid_attributes
      get edit_appoinment_type_url(appoinment_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AppoinmentType" do
        expect {
          post appoinment_types_url, params: { appoinment_type: valid_attributes }
        }.to change(AppoinmentType, :count).by(1)
      end

      it "redirects to the created appoinment_type" do
        post appoinment_types_url, params: { appoinment_type: valid_attributes }
        expect(response).to redirect_to(appoinment_type_url(AppoinmentType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AppoinmentType" do
        expect {
          post appoinment_types_url, params: { appoinment_type: invalid_attributes }
        }.to change(AppoinmentType, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post appoinment_types_url, params: { appoinment_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested appoinment_type" do
        appoinment_type = AppoinmentType.create! valid_attributes
        patch appoinment_type_url(appoinment_type), params: { appoinment_type: new_attributes }
        appoinment_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the appoinment_type" do
        appoinment_type = AppoinmentType.create! valid_attributes
        patch appoinment_type_url(appoinment_type), params: { appoinment_type: new_attributes }
        appoinment_type.reload
        expect(response).to redirect_to(appoinment_type_url(appoinment_type))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        appoinment_type = AppoinmentType.create! valid_attributes
        patch appoinment_type_url(appoinment_type), params: { appoinment_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested appoinment_type" do
      appoinment_type = AppoinmentType.create! valid_attributes
      expect {
        delete appoinment_type_url(appoinment_type)
      }.to change(AppoinmentType, :count).by(-1)
    end

    it "redirects to the appoinment_types list" do
      appoinment_type = AppoinmentType.create! valid_attributes
      delete appoinment_type_url(appoinment_type)
      expect(response).to redirect_to(appoinment_types_url)
    end
  end
end
